name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install mdb tools
        run: apt install -y mdbtools unixodbc-dev

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: install dependencies
        run: pip install -r data/requirements.txt
    
      - name: test pipeline
        working-directory: ./project
        run: |
          ls -la
          ./tests.sh
        shell: bash

