name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
    	with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: install dependencies
        run: pip install -r data/requirements.txt
    
      - name: test pipeline
	with:
          path: project
        run: ./test.sh
